apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - k8s/base/deployment.yaml
  - k8s/base/service.yaml
images:
  - name: nextjs-second
  - newTag: efbe47b0c711f9d1f6a005ebf5d46f3f68ec9793
  #${COMMIT_SHA}